export default {
  "TAKE_SUGGESTION": "TAKE_SUGGESTION",
  "SEARCH_DRUGS": "SEARCH_DRUGS",
  "PICK_CONDITION": "PICK_CONDITION",
  "PICK_DRUG": "PICK_DRUG",
  "PREVIOUS_STEP": "PREVIOUS_STEP",
  "SELECT_DATE": "SELECT_DATE",
  "OFFER_DATES": "OFFER_DATES",
  "TOGGLE_DATE_ENABLED": "TOGGLE_DATE_ENABLED",
  "MOVE_DRUG_CURSOR": "MOVE_DRUG_CURSOR",
  "NEW_HASH_STATE": "NEW_HASH_STATE",
  "BODY_CLICK": "BODY_CLICK",
  "RESET_HOOKS": "RESET_HOOKS",
  "QUICK_ADD_HOOK": "QUICK_ADD_HOOK",
  "NEW_HOOK": "NEW_HOOK",
  "EDIT_HOOK": "EDIT_HOOK",
  "SAVE_HOOK": "SAVE_HOOK",
  "DELETE_HOOK": "DELETE_HOOK",
  "LOADED": "LOADED",
  "NEW_SIG": "NEW_SIG",
  "EXTERNAL_APP_RETURNED": "EXTERNAL_APP_RETURNED",
  "SET_ACTIVITY": "SET_ACTIVITY",
  "CHANGE_FHIR_SERVER": "CHANGE_FHIR_SERVER"
};


