export default {
  "SEARCH_DRUGS": "SEARCH_DRUGS",
  "PICK_DRUG": "PICK_DRUG",
  "PREVIOUS_STEP": "PREVIOUS_STEP",
  "SELECT_DATE": "SELECT_DATE",
  "MOVE_DRUG_CURSOR": "MOVE_DRUG_CURSOR",
  "NEW_HASH_STATE": "NEW_HASH_STATE"
};


